version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped